version: '3.7'

networks:
  microservice-net :
    driver: bridge
services:
  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./volumes/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./volumes/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources


  user-service:
    build: user-service/.
    env_file:
      - ".env"
    networks:
      - microservice-net
    container_name: user-service-container
    ports:
      - "8083:8080"
  transaction-service:
    build: transaction-service/.
    env_file:
      - ".env"
    networks:
      - microservice-net
    container_name: transaction-service-container
    ports:
      - "8085:8080"
  account-service:
    build: account-service/.
    env_file:
      - ".env"
    networks:
      - microservice-net
    container_name: account-service-container
    ports:
      - "8085:8080"
    depends_on:
      - user-service
      - transaction-service

