spring.application.name=transaction-service
server.port=8084

spring.profiles.active=default
## CONFIG SERVER CONFIGURATION
spring.config.import="optional:configserver:http://localhost:9999"

eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://${TRANSACTION_SERVICE_EUREKA_SERVER_HOST}:8761/eureka/



