spring.application.name=discovery-service
server.port=8761

spring.cloud.discovery.enabled=true
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false
eureka.server.enable-self-preservation=false


spring.cloud.config.enabled=false

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoints.web.base-path=/actuator