spring.application.name=account-service
server.port=8085
spring.profiles.active=default
spring.config.import=optional:configserver:http://localhost:9999

eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://${ACCOUNT_SERVICE_EUREKA_SERVER_HOST}:8761/eureka/


